task:
  auto_cancellation: false
  matrix:
    - name: JDK Job
      container:
        image: gradle:jdk8
      script: javac main.java
    - name: Python Job
      container:
        image: jumbocakeyumyum/flake8:latest
      script: flake8 *.py
    - name: NodeJS Job
      container:
        image: node:latest
      script: npm test
    - name: Alpine Job
      container:
        image: alpine:latest
      prepare_script: apk add bash && chmod +x main.sh
      script: bash main.sh && chmod -x main.sh
    - name: Haskell Job
      container:
        image: haskell:latest
      script: ghci main.hs
    - name: Ruby Job
      osx_instance:
        image: mojave-xcode-10.1
      script: chmod +x main.rb && ruby main.rb
    - name: Lua Job
      container:
        image: superpaintman/lua:latest
      env:
        LUAFILE: main.lua
      script: lua ./$LUAFILE
