task:
  auto_cancellation: false
  matrix:
    - name: JDK Job
      container:
        image: gradle:jdk8
      script: javac main.java
    - name: Python Job
      container:
        image: jumbocakeyumyum/flake8:latest
      script: flake8 *.py
    - name: NodeJS Job
      container:
        image: node:latest
      script: npm test
