task:
  auto_cancellation: false
  matrix:
    - name: JDK-8 Job
      container:
        image: gradle:jdk8
      script: javac main.java
    - name: JDK-9 Job
      container:
        image: gradle:jdk9
      script: javac main.java
    - name: Python Job
      container:
        image: jumbocakeyumyum/flake8:latest
      script: flake8 *.py
    - name: NodeJS-Latest Job
      container:
        image: node:latest
      script: npm test
    - name: Alpine Job
      container:
        image: alpine:latest
      prepare_script: apk add bash && chmod +x main.sh
      script: bash main.sh && chmod -x main.sh
    - name: Haskell Job
      container:
        image: haskell:latest
      script: ghci main.hs
    - name: Ruby Job
      osx_instance:
        image: mojave-xcode-10.1
      script: chmod +x main.rb && ruby main.rb
    - name: Lua Job
      container:
        image: superpaintman/lua:latest
      env:
        LUAFILE: main.lua
      script: lua ./$LUAFILE
    - name: Makefile Job
      container:
        image: python:latest
      script: make
    - name: Crystal Job
      container:
        image: crystallang/crystal:latest
      script: crystal run main.cr
    - name: CoffeeScript Job
      container:
        image: node:dubnium
      prep_script: npm install -g coffeescript
      script: coffee -M main.coffee
    - name: Golang-12 Job
      container:
        image: golang:1.12.1-alpine3.9
      script: go run main.go
    - name: Golang-11 Job
      container:
        image: golang:1.11.6-alpine3.9
      script: go run main.go
